import type { AchievementDef } from "./achievement.types.js";

export const ACHIEVEMENTS: AchievementDef[] = [
  // ════════════════════════════════════════════════════════════
  // BEGINNER
  // ════════════════════════════════════════════════════════════
  {
    id: "first-solve",
    category: "BEGINNER",
    name: "First Solve",
    description: "Complete your first solve",
    icon: "cube",
    rarity: "common",
    points: 5,
    parentId: null,
    criteria: { type: "solves_count", target: 1 },
    order: 0,
  },
  {
    id: "solve-under-120",
    category: "BEGINNER",
    name: "Breaking the Ice",
    description: "Solve in under 2 minutes",
    icon: "stopwatch",
    rarity: "common",
    points: 10,
    parentId: "first-solve",
    criteria: { type: "best_time", target: 120_000 },
    order: 1,
  },
  {
    id: "solve-under-90",
    category: "BEGINNER",
    name: "Speed Puzzler",
    description: "Solve in under 90 seconds",
    icon: "stopwatch",
    rarity: "common",
    points: 15,
    parentId: "solve-under-120",
    criteria: { type: "best_time", target: 90_000 },
    order: 2,
  },
  {
    id: "solve-under-60",
    category: "BEGINNER",
    name: "Sub-Minute Club",
    description: "Solve in under 60 seconds",
    icon: "lightning",
    rarity: "rare",
    points: 25,
    parentId: "solve-under-90",
    criteria: { type: "best_time", target: 60_000 },
    order: 3,
  },
  {
    id: "solve-under-45",
    category: "BEGINNER",
    name: "Quick Hands",
    description: "Solve in under 45 seconds",
    icon: "lightning",
    rarity: "rare",
    points: 35,
    parentId: "solve-under-60",
    criteria: { type: "best_time", target: 45_000 },
    order: 4,
  },
  {
    id: "solve-under-30",
    category: "BEGINNER",
    name: "Speed Demon",
    description: "Solve in under 30 seconds",
    icon: "bolt",
    rarity: "epic",
    points: 50,
    parentId: "solve-under-45",
    criteria: { type: "best_time", target: 30_000 },
    order: 5,
  },

  // ════════════════════════════════════════════════════════════
  // PRACTICE
  // ════════════════════════════════════════════════════════════
  {
    id: "solves-10",
    category: "PRACTICE",
    name: "Getting Started",
    description: "Complete 10 practice solves",
    icon: "cube-stack",
    rarity: "common",
    points: 5,
    parentId: null,
    criteria: { type: "solves_count", target: 10 },
    order: 0,
  },
  {
    id: "solves-50",
    category: "PRACTICE",
    name: "Dedicated",
    description: "Complete 50 practice solves",
    icon: "cube-stack",
    rarity: "common",
    points: 15,
    parentId: "solves-10",
    criteria: { type: "solves_count", target: 50 },
    order: 1,
  },
  {
    id: "solves-100",
    category: "PRACTICE",
    name: "Century",
    description: "Complete 100 practice solves",
    icon: "layers",
    rarity: "rare",
    points: 30,
    parentId: "solves-50",
    criteria: { type: "solves_count", target: 100 },
    order: 2,
  },
  {
    id: "solves-500",
    category: "PRACTICE",
    name: "Devoted",
    description: "Complete 500 practice solves",
    icon: "layers",
    rarity: "epic",
    points: 50,
    parentId: "solves-100",
    criteria: { type: "solves_count", target: 500 },
    order: 3,
  },

  // ════════════════════════════════════════════════════════════
  // SPEED
  // ════════════════════════════════════════════════════════════
  {
    id: "sub-25",
    category: "SPEED",
    name: "Blazing Fingers",
    description: "Achieve a sub-25 second solve",
    icon: "bolt",
    rarity: "rare",
    points: 25,
    parentId: null,
    criteria: { type: "best_time", target: 25_000 },
    order: 0,
  },
  {
    id: "sub-20",
    category: "SPEED",
    name: "Prodigy",
    description: "Achieve a sub-20 second solve",
    icon: "zap",
    rarity: "rare",
    points: 35,
    parentId: "sub-25",
    criteria: { type: "best_time", target: 20_000 },
    order: 1,
  },
  {
    id: "sub-15",
    category: "SPEED",
    name: "Elite",
    description: "Achieve a sub-15 second solve",
    icon: "zap",
    rarity: "epic",
    points: 50,
    parentId: "sub-20",
    criteria: { type: "best_time", target: 15_000 },
    order: 2,
  },
  {
    id: "sub-12",
    category: "SPEED",
    name: "Speed Legend",
    description: "Achieve a sub-12 second solve",
    icon: "flame",
    rarity: "epic",
    points: 65,
    parentId: "sub-15",
    criteria: { type: "best_time", target: 12_000 },
    order: 3,
  },
  {
    id: "sub-10",
    category: "SPEED",
    name: "Sub-10 Club",
    description: "Achieve a sub-10 second solve",
    icon: "gold-bolt",
    rarity: "legendary",
    points: 100,
    parentId: "sub-12",
    criteria: { type: "best_time", target: 10_000 },
    order: 4,
  },

  // ════════════════════════════════════════════════════════════
  // COMPETITIVE
  // ════════════════════════════════════════════════════════════
  {
    id: "first-ranked-match",
    category: "COMPETITIVE",
    name: "Welcome to Ranked",
    description: "Play your first ranked match",
    icon: "trophy",
    rarity: "common",
    points: 10,
    parentId: null,
    criteria: { type: "ranked_matches", target: 1 },
    order: 0,
  },
  {
    id: "first-ranked-win",
    category: "COMPETITIVE",
    name: "First Victory",
    description: "Win your first ranked match",
    icon: "trophy",
    rarity: "common",
    points: 15,
    parentId: "first-ranked-match",
    criteria: { type: "ranked_wins", target: 1 },
    order: 1,
  },
  {
    id: "streak-3",
    category: "COMPETITIVE",
    name: "On a Roll",
    description: "Win 3 ranked matches in a row",
    icon: "fire-trophy",
    rarity: "rare",
    points: 30,
    parentId: "first-ranked-win",
    criteria: { type: "win_streak", target: 3 },
    order: 2,
  },
  {
    id: "streak-5",
    category: "COMPETITIVE",
    name: "Unstoppable",
    description: "Win 5 ranked matches in a row",
    icon: "fire-trophy",
    rarity: "epic",
    points: 50,
    parentId: "streak-3",
    criteria: { type: "win_streak", target: 5 },
    order: 3,
  },
  {
    id: "elo-1200",
    category: "COMPETITIVE",
    name: "Bronze Medalist",
    description: "Reach 1200 Elo rating",
    icon: "bronze-medal",
    rarity: "rare",
    points: 25,
    parentId: "first-ranked-win",
    criteria: { type: "elo_reached", target: 1200 },
    order: 4,
  },
  {
    id: "elo-1500",
    category: "COMPETITIVE",
    name: "Silver Medalist",
    description: "Reach 1500 Elo rating",
    icon: "silver-medal",
    rarity: "epic",
    points: 50,
    parentId: "elo-1200",
    criteria: { type: "elo_reached", target: 1500 },
    order: 5,
  },
  {
    id: "elo-1800",
    category: "COMPETITIVE",
    name: "Gold Medalist",
    description: "Reach 1800 Elo rating",
    icon: "gold-medal",
    rarity: "legendary",
    points: 100,
    parentId: "elo-1500",
    criteria: { type: "elo_reached", target: 1800 },
    order: 6,
  },

  // ════════════════════════════════════════════════════════════
  // MASTERY
  // ════════════════════════════════════════════════════════════
  {
    id: "avg5-under-20",
    category: "MASTERY",
    name: "Consistent Prodigy",
    description: "Achieve an average of 5 under 20 seconds",
    icon: "stopwatch",
    rarity: "epic",
    points: 50,
    parentId: null,
    criteria: { type: "avg_of_5", target: 20_000 },
    order: 0,
  },
  {
    id: "avg12-under-20",
    category: "MASTERY",
    name: "Consistency King",
    description: "Achieve an average of 12 under 20 seconds",
    icon: "stopwatch",
    rarity: "epic",
    points: 65,
    parentId: "avg5-under-20",
    criteria: { type: "avg_of_12", target: 20_000 },
    order: 1,
  },
  {
    id: "tps-above-5",
    category: "MASTERY",
    name: "Fluent Turner",
    description: "Achieve an average TPS above 5",
    icon: "zap",
    rarity: "rare",
    points: 30,
    parentId: null,
    criteria: { type: "avg_tps", target: 5_000 },
    order: 2,
  },
  {
    id: "tps-above-7",
    category: "MASTERY",
    name: "Speed Turner",
    description: "Achieve an average TPS above 7",
    icon: "flame",
    rarity: "legendary",
    points: 75,
    parentId: "tps-above-5",
    criteria: { type: "avg_tps", target: 7_000 },
    order: 3,
  },

  // ════════════════════════════════════════════════════════════
  // SOCIAL
  // ════════════════════════════════════════════════════════════
  {
    id: "first-friend",
    category: "SOCIAL",
    name: "Social Butterfly",
    description: "Add your first friend",
    icon: "user-plus",
    rarity: "common",
    points: 10,
    parentId: null,
    criteria: { type: "friends_count", target: 1 },
    order: 0,
  },
  {
    id: "private-match",
    category: "SOCIAL",
    name: "Private Match",
    description: "Play a private match with someone",
    icon: "handshake",
    rarity: "common",
    points: 10,
    parentId: "first-friend",
    criteria: { type: "private_matches", target: 1 },
    order: 1,
  },
  {
    id: "spectate-match",
    category: "SOCIAL",
    name: "Spectator",
    description: "Spectate another player's match",
    icon: "eye",
    rarity: "common",
    points: 15,
    parentId: "private-match",
    criteria: { type: "spectate_matches", target: 1 },
    order: 2,
  },

  // ════════════════════════════════════════════════════════════
  // SPECIAL
  // ════════════════════════════════════════════════════════════
  {
    id: "birthday-solve",
    category: "SPECIAL",
    name: "Birthday Cuber",
    description: "Complete a solve on your birthday",
    icon: "cake",
    rarity: "epic",
    points: 50,
    hidden: true,
    parentId: null,
    criteria: { type: "birthday_solve", target: 1 },
    order: 0,
  },
  {
    id: "night-owl",
    category: "SPECIAL",
    name: "Night Owl",
    description: "Complete a solve between midnight and 5 AM",
    icon: "moon",
    rarity: "rare",
    points: 25,
    hidden: true,
    parentId: null,
    criteria: { type: "night_owl", target: 1 },
    order: 1,
  },
  {
    id: "comeback-victory",
    category: "SPECIAL",
    name: "Comeback King",
    description: "Win a match after being behind",
    icon: "phoenix",
    rarity: "epic",
    points: 40,
    hidden: true,
    parentId: null,
    criteria: { type: "reverse_sweep", target: 1 },
    order: 2,
  },
  {
    id: "google-login",
    category: "SPECIAL",
    name: "Googler",
    description: "Sign in with Google",
    icon: "google",
    rarity: "common",
    points: 10,
    hidden: true,
    parentId: null,
    criteria: { type: "google_login", target: 1 },
    order: 3,
  },
];

export const ACHIEVEMENT_MAP = new Map<string, AchievementDef>(
  ACHIEVEMENTS.map((a) => [a.id, a])
);

export const CATEGORY_ORDER: Record<string, number> = {
  BEGINNER: 0,
  PRACTICE: 1,
  SPEED: 2,
  COMPETITIVE: 3,
  MASTERY: 4,
  SOCIAL: 5,
  SPECIAL: 6,
};

export function totalAchievementPoints(): number {
  return ACHIEVEMENTS.reduce((sum, a) => sum + a.points, 0);
}
